# Generated by Django 5.0.6 on 2024-07-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('rut', models.IntegerField(blank=True, null=True, unique=True)),
                ('cargo', models.CharField(choices=[('geologo', 'Geologo'), ('especialista_auditor', 'Especialista Auditor'), ('tecnico_instrumentista', 'Tecnico Instrumentista')], default='geologo', max_length=150, verbose_name='Cargo')),
                ('departamento', models.CharField(choices=[('ingenieria', 'Ingenieria '), ('seguridad', 'Seguridad'), ('programacion_y_control', 'Programacion y Control')], default='ingenieria', max_length=150, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': '1.Trabajadores',
                'db_table': 'Trabajadores',
                'permissions': [],
            },
        ),
    ]
